install: true
git:
  submodules: false
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap
branches:
  only:
    - master
language: objective-c
osx_image: xcode8.3
xcode_project: TDDKATA.xcodeproj
xcode_scheme: TDDKATATests
script:
  - xcodebuild test -project TDDKATA.xcodeproj -scheme TDDKATA -destination 'platform=iOS Simulator,name=iPhone 7'
